//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalPG2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Videogames
    {
        public int VG_ID { get; set; }
        public string VG_Nombre { get; set; }
        public System.DateTime VG_FechaCompra { get; set; }
        public int VG_Precio { get; set; }
        public string VG_Estudio { get; set; }
    }
}
